repositories:
  remote:
    - https://stocksoftware.jfrog.io/stocksoftware/staging
    - https://repo.maven.apache.org/maven2
    - https://stocksoftware.jfrog.io/stocksoftware/maven2

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  # GWT deps
  gwt_user: com.google.gwt:gwt-user:jar:2.9.0
  gwt_dev: com.google.gwt:gwt-dev:jar:2.9.0

  jsinterop_annotations: org.realityforge.com.google.jsinterop:jsinterop-annotations:jar:2.8.2-v20191108

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0

  elemental2_promise: org.realityforge.com.google.elemental2:elemental2-promise:jar:2.27
  elemental2_core: org.realityforge.com.google.elemental2:elemental2-core:jar:2.27
  elemental2_dom: org.realityforge.com.google.elemental2:elemental2-dom:jar:2.27

  braincheck: org.realityforge.braincheck:braincheck:jar:1.26.0

  grim_annotations: org.realityforge.grim:grim-annotations:jar:0.04
  grim_processor: org.realityforge.grim:grim-processor:jar:0.04

  javax_json: org.glassfish:javax.json:jar:1.1

  galdr_core: org.realityforge.galdr:galdr-core:jar:0.03
  galdr_processor: org.realityforge.galdr:galdr-processor:jar:0.03
